### ISSUE TITLE
I tried it to see if it can burn BDD features. It did not work.

### ISSUE THREAD

**Issue by aomaryus** [cypress-io/cypress-grep#104]
I tried it to see if it can burn BDD features. It did not work.

**Comment by bahmutov** [comment]
Can you provide more details? Like an example project, the expected output and the actual output

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
