### ISSUE TITLE
How can I use the plugin with another env for config file?

### ISSUE THREAD

**Issue by Oaky78** [cypress-io/cypress-grep#107]
I use env for my config file.

This is a part of the script for my pipeline. 
`npx cypress run --record --parallel --ci-build-id "$(Build.BuildId)" --env $(stage)=true --config-file`

In Cypress Plugins I use another Plugin from you:

`module.exports = (on, config) => {`
  `require('cypress-grep/src/plugin')(config);`
  `return require('@bahmutov/cypress-extends')(config.configFile);`
}`

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
