### ISSUE TITLE
enable grep AND condition for search using multiple substrings

### ISSUE THREAD

**Issue by petermsouzajr** [cypress-io/cypress-grep#112]
## Functionality currently in docs:
run all tests with "hello world" or "auth user" in their title
`$ npx cypress run --env grep="hello world; auth user"`

## Additional functionality desired:
only run tests with both "hello world" and "auth user" in their title
`$ npx cypress run --env grep="hello world: auth user"`

**Comment by RomanOsadchi** [comment]
same issue:
Cypress 9.5.0
"cypress-grep": "^2.13.1"

npx cypress run -P ./apps/sales-e2e --spec **/smoke/admin.js --env grepTags="@1 @2" - doesn't work, runs only tests with @1 

But it works without npx:
cypress run -P ./apps/sales-e2e --spec **/smoke/admin.js --env grepTags="@1 @2" - work

**Comment by HibaBarakat** [comment]
Hi there, i need to ask you when using grep ..  are you using JS specs or TS scripts 
Also i want to ask you if possible, when you run your code with grep does it run "before" un-needed specs ? even though i added not to run them

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
