### ISSUE TITLE
grep=EXAMPLE doesn't work if the very first test in the spec doesn't have EXAMPLE in the title

### ISSUE THREAD

**Issue by ac10qa** [cypress-io/cypress-grep#114]
I had to add a dummy test at 1st position to fix this problem.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
