### ISSUE TITLE
All tests in spec run when only one is tagged

### ISSUE THREAD

**Issue by dsteinbach-ep** [cypress-io/cypress-grep#115]
Just testing out this package but I cannot get a simple example to work. This is my spec:

```
describe('My test suite', () => {
  it(`a`, () => {
    ...
  });

  it(`b`, () => {
    ...
  });

  it(`c`, () => {
    ...
  });

  it(`d`, { tags: ['smoke'] }, () => {
    ...
  });

  it('e', () => {
    ...
  });
});
```

The commands below run **all tests** in the spec above (but successfully skips other specs):
```
yarn cypress:run --env grepTags="smoke",grepFilterSpecs=true
yarn cypress:run --env grepTags="smoke"
yarn cypress:run --env grep="e"
```

Environment:
```
Cypress: 9.4.1
Node: 12.22.8
```

Other Cypress plugins installed:
```
@cypress/webpack-preprocessor
@cypress/code-coverage/task
```

**Comment by bahmutov** [comment]
Can you enable the debug logs? What happens when you use `cypress open --env grepTags="smoke"`, does it show the right settings in the "env" object?

**Comment by dsteinbach-ep** [comment]
With "cypress open" i do see it filters out all the specs except the one with that has the test tagged as "smoke" but when I run the spec it runs all the tests even if they aren't tagged.
 
I do see the correct env variables set in Settings:
![Screen Shot 2022-03-04 at 3 48 54 PM](https://user-images.githubusercontent.com/95725195/156857077-2c70eaa8-2894-4e39-b15e-95c604260d3f.png)

**Comment by dsteinbach-ep** [comment]
Ahhh... fixed it!

In `cypress/support/index.ts` i had to change:
```
import 'cypress-grep';
```
to
```
require('cypress-grep')();
```

Everything works great after that. Thanks!

**Comment by bahmutov** [comment]
:)
