### ISSUE TITLE
Order is different from normal run with subFolders

### ISSUE THREAD

**Issue by Narretz** [cypress-io/cypress-grep#118]
Very minor, but may be confusing when you first use the plugin.
i.e if you have the following structure:

spec
folder1/spec
folder1/subfolder/spec
folder2/spec

normal cypress runs it in this order.

When you use grep, it runs it in this order:
spec
folder1/spec
folder2/spec
folder1/subfolder/spec

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
