### ISSUE TITLE
How to differentiate results based on tags for test run statistic?

### ISSUE THREAD

**Issue by violant** [cypress-io/cypress-grep#121]
How to differentiate results based on tags? 
For example I run tests with several tags: tag1, tag2, tag3 and want to get result counts of passed, failed, etc tests by tag name.
There are not tags information in results object after cypress.run using cypress module API.
It could be there is different way to do this.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
