### ISSUE TITLE
cypress open --env grepUntagged=true [shows all the specs, including the taged ones]

### ISSUE THREAD

**Issue by h2oearth** [cypress-io/cypress-grep#123]
This is my test structure
```
root/cypress/integration/*.js <- untagged (10 tests)
root/cypress/integration/qa/*.js <-tagged (1 test)
```

**Cypress run**
cypress run works as expected when I pass either one of this env parameters `--env grepTags='@qa'` or ` --env grepUntagged=true`.

**Cypress open**
cypress open show all the specs, even if I pass `--env grepUntagged=true`. I attached a snapshot of the cypress configuration.

Any idea of what else to try?

<img width="306" alt="Screen Shot 2022-04-20 at 9 58 29 am" src="https://user-images.githubusercontent.com/97860372/164120272-139b6a05-bbab-43b4-8bb9-96e7c21d6248.png">

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
