### ISSUE TITLE
Filter out to run only 1 test from the rest of the loop

### ISSUE THREAD

**Issue by quad5** [cypress-io/cypress-grep#125]
We have a suite (`describe`) consists of a few tests (`it`). On top of that suite, we have a for loop to iterate through that suite.

We are using `cypress-grep` to filter out a handful of tests for `smoke test` or `acceptance test` run. Is it possible to filter out or run only 1 test in said loop?

**Comment by bahmutov** [comment]
Can you provide an example spec showing what you run and how you write your spec?

**Comment by quad5** [comment]
> for (const [key, value] of Object.entries(allUserTypes)) {
    describe(`xyz`, function() {

        before(function() {
            value().then(function(param) {
                somefunction()
            })
        })

        it('test 1', function() {
            ...
        })

        it('test 2', function() {
           ...
        })

        it('test 3', {tags: [SMOKE_TEST]}, function() {
            ...
        })

        it('test 4', function() {
            ...
        })

        it('test 5', function() {
            ...
        })
   })
}

**Comment by bahmutov** [comment]
And which test you want to run?

**Comment by quad5** [comment]
it('test 3', {tags: [SMOKE_TEST]}, function() {}

**Comment by mfrma-moura** [comment]
@nthypes

**Comment by DPC15038** [comment]
https://github.com/cypress-io/cypress/issues/24451

I also submitted an issue for this. This feels like such a useful case, but it is not supported.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
