### ISSUE TITLE
Unexpected behavior of explicit not tag when used alone

### ISSUE THREAD

**Issue by gofr** [cypress-io/cypress-grep#129]
With the new explicit-not tag from #122, I expected to be able to do something like this in our CI: `--env grepTags='$VAR --@flaky'`, where `VAR` is a variable that depends on context and could be, for example, `@smoke` if I want to run all the smoke tests (except the flaky ones), or _empty_ if I want to run _all_ the tests (except the flaky ones).

`@smoke --@flaky` works great. But just `--@flaky` on its own does _not_ exclude the flaky tests. It runs all the tests.

I can do `$VAR @non-existent --@flaky` or `$VAR -@flaky --@flaky` as a work-around to make it work.

I guess this is because ORS_filtered in https://github.com/cypress-io/cypress-grep/blob/1a2bd3449819f71f46ba1e49a7db90081b2d799f/src/utils.js#L80 is empty, so the `explicitNotTags` end up not being added to anything. Should they be?

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
