### ISSUE TITLE
Cypress-greps does not work with tags which are Enum

### ISSUE THREAD

**Issue by thanhtuantran84** [cypress-io/cypress-grep#131]
Hi,
It seems to me that cypress-grep does not work when I define test scenarios using enum like below
`describe("Test1", () => {
    it(
        "Test1 successful",
        { tags: [TestGroup.E2E, TestGroup.SMOKE] },
        () => {
            cy.get(".abc").should("exist");
        },
    );
});
`
Do we have the plan to support it?

**Comment by o3-steven** [comment]
@thanhtuantran84 you want to show a minimal reproducible example for this? I might take some time and look into it

**Comment by akosradler** [comment]
Hello, as I am experiencing the same issue: it seems to only fail when there are enums in an array. If it was a single tag, the tag would get recognized.

**Comment by praveenpandey02** [comment]
Is there any update on this? looks like a lot of people are having this issue.

**Comment by bahmutov** [comment]
The tags / enums that are dynamic (meaning their value cannot be determined easily by looking at the spec file) are not supported by this plug-in. If you have any idea how to implement it I’m open to an idea of course

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
