### ISSUE TITLE
Incompatible error is wrong

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress-grep#132]
`Error: Incompatible versions detected, cypress-grep 2.0.0+ requires Cypress 10.0.0+`
is what I got when I mistakenly installed the newest version
It should be `3.0.0`

**Comment by byrond** [comment]
I received this as well when I installed cypress-grep 3.0.1 and cypress 10.3.0.

**Comment by Songyu-Wang** [comment]
Fix PR created, but its closed because I dont want a fork exist on in my repo list. Feel free to reopen and land the PR

**Comment by nemanjaglumac** [comment]
Looking at the changelog in [releases](https://github.com/cypress-io/cypress-grep/releases/tag/v3.0.0) makes this even more confusing. It says that v3 will support only Cypress configs **less than or equal to** Cypress 10 😕 

Was it supposed to say that the breaking change in v3 is that is supports only Cyperss 10 and greater versions instead? cc @bahmutov

**Comment by gili-lumigo** [comment]
I'm having the same issue with cypress 10.3.0 & cypress-grep 3.0.2.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
