### ISSUE TITLE
Grep is not working.

### ISSUE THREAD

**Issue by zubair-shahid-formsoft-inc-com** [cypress-io/cypress-grep#134]
./node_modules/.bin/cypress run --env grepTags="Smoke" 
Above command is running all of the tests.

**Comment by BelRaz** [comment]
I have the same issue

**Comment by mmitchell3590** [comment]
Same here. I also use the in "open" view and it is including all .js files even though I see this in console:
```cypress-grep: filtering using tag(s) "@webAppMonitor"
cypress-grep: will omit filtered tests
grep and/or grepTags has eliminated all specs
grepTags: @webAppMonitor
Will leave all specs to run to filter at run-time```

**Comment by bahmutov** [comment]
FYI I have upgraded my example to Cypress v10 and cypress-grep@3 and it is working as expected, see the update PR https://github.com/bahmutov/cypress-grep-example/pull/79 To debug your problem we would need a reproducible example. My advice is to look at the debugging logging, maybe you can notice where the things go wrong https://github.com/cypress-io/cypress-grep#debugging-in-the-plugin

**Comment by zubair-shahid-formsoft-inc-com** [comment]
> FYI I have upgraded my example to Cypress v10 and cypress-grep@3 and it is working as expected, see the update PR [bahmutov/cypress-grep-example#79](https://github.com/bahmutov/cypress-grep-example/pull/79) To debug your problem we would need a reproducible example. My advice is to look at the debugging logging, maybe you can notice where the things go wrong https://github.com/cypress-io/cypress-grep#debugging-in-the-plugin

I am using Cypress V10.0.3 and cypress-grep V3.0.1, still facing the same issue.
Secondly, Running DEBUG=cypress-grep npx cypress run --env grep=works,grepFilterSpecs=true, does not shows any messages related to the plugin in the terminal output

**Comment by mmitchell3590** [comment]
I double checked the plugin installation, and at least in my case it seems ok.

Here my e2e.js
<img width="432" alt="e2e js_-_aristamd_-_Visual_Studio_Code_202207051657051279" src="https://user-images.githubusercontent.com/25928813/177408106-4e5ab050-7bc8-4ed9-b69a-d0f04e821316.png">

Here is my cypress.config.js
<img width="369" alt="cypress config js_-_aristamd_-_Visual_Studio_Code_202207051657051384" src="https://user-images.githubusercontent.com/25928813/177408175-1386ce36-07da-4409-a43a-a2b3275df58b.png">

Here is output where it is finding all files in project now. I am only expecting 3 matches
<img width="376" alt="package json_-_aristamd_-_Visual_Studio_Code_202207051657051809" src="https://user-images.githubusercontent.com/25928813/177408232-81a4bac3-f34a-4f2b-898e-1d502ecb929e.png">

**Comment by bahmutov** [comment]
@mmitchell3590 can you enable debugging logs via `DEBUG` environment variable, please https://github.com/cypress-io/cypress-grep#debugging-in-the-plugin and see what it gives you?

**Comment by mmitchell3590** [comment]
Here is the output:

```
  cypress-grep cypress-grep plugin version 3.0.1 +0ms
  cypress-grep Cypress config env object: { ...DEBUG: 'cypress-grep', grepTags: '@webAppMonitor', grepFilterSpecs: true, grepOmitFiltered: true } +1ms  
cypress-grep: filtering using tag(s) "@webAppMonitor"
cypress-grep: will omit filtered tests
  cypress-grep parsed grep tags [ [ { tag: '@webAppMonitor', invert: false } ] ] +7ms
  cypress-grep specPattern **/*.* +4ms
  cypress-grep excludeSpecPattern *.hot-update.js +0ms
  cypress-grep integrationFolder C:\Users\matt_local\project\cypress-test\config\monitor\subproject +0ms
  cypress-grep found 1 spec files +21ms
  cypress-grep [ 'C:/Users/matt_local/project/cypress-test/config/monitor/subproject/cypress.config.js' ] +0ms
  cypress-grep parsed grep tags { title: [], tags: [ [ [Object] ] ] } +2ms
  cypress-grep spec file C:/Users/matt_local/project/cypress-test/config/monitor/subproject/cypress.config.js +61ms
  cypress-grep test info: [] +0ms
  cypress-grep found grep tags "@webAppMonitor" in 0 specs +0ms
  cypress-grep [] +1ms
grep and/or grepTags has eliminated all specs
grepTags: @webAppMonitor
Will leave all specs to run to filter at run-time
```

**Comment by bahmutov** [comment]
ok, so it seems it might not even find the config file correctly - can I ask about the repo setup? Where are the files package.json and cypress.config.js and the tests? Are they like this:
```
cypress-test/
  package.json
  config/
     monitor/
        subproject/
           cypress.config.js
           cypress/
              e2e/
                 spec1.cy.js
                 spec2.cy.js 
                 ...
```

**Comment by mmitchell3590** [comment]
It is like this:

```
cypress-test/
  package.json
  config/
     monitor/
        subproject/
           cypress.config.js
  cypress/
      integration/
               spec1.cy.js
               spec2.cy.js 
           
```

**Comment by bahmutov** [comment]
And what’s the cypress.config.js spec pattern?

**Comment by zubair-shahid-formsoft-inc-com** [comment]
Here is my cypress.config.js
<img width="630" alt="Screenshot 2022-07-06 at 2 41 40 PM" src="https://user-images.githubusercontent.com/105410226/177521897-385a412d-765d-4cd7-8cd2-3bde611ca953.png">

That's my project hierarchy
 
<img width="326" alt="Screenshot 2022-07-06 at 2 44 44 PM" src="https://user-images.githubusercontent.com/105410226/177522129-a3ce091f-c90b-4866-a247-933062a280b7.png">

Here is my terminal output: 
<img width="1399" alt="Screenshot 2022-07-06 at 2 46 17 PM" src="https://user-images.githubusercontent.com/105410226/177522534-accba5ca-4bd8-4719-83e6-663bf1916a64.png">

Here is my package.json
<img width="388" alt="Screenshot 2022-07-06 at 2 47 35 PM" src="https://user-images.githubusercontent.com/105410226/177522668-21555294-c412-44dc-ac53-3a69aea22588.png">



> Make sure you have installed the plugin correctly, see https://github.com/cypress-io/cypress-grep#install

**Comment by mmitchell3590** [comment]
@bahmutov  specPattern is: `**/*.*`

**Comment by GilbertoGNG** [comment]
I think the problem comes when cypress-grep is setting the integrationFolder constant. if your cypress.config.js is not in the cypress folder then the plugin won't find your tests.

https://github.com/cypress-io/cypress-grep/blob/2568aebbe43291c1015afb1ae549403176498157/src/plugin.js#L55

So just set an environment variable called grepIntegrationFolder pointing to the cypress folder. That's how I made it work.

![image](https://user-images.githubusercontent.com/53126224/178961298-e07475ba-3801-4da3-90d8-0a999146d14c.png)

I hope this help someone 😁

**Comment by zubair-shahid-formsoft-inc-com** [comment]
> I think the problem comes when cypress-grep is setting the integrationFolder constant. if your cypress.config.js is not in the cypress folder then the plugin won't find your tests.
> 
> https://github.com/cypress-io/cypress-grep/blob/2568aebbe43291c1015afb1ae549403176498157/src/plugin.js#L55
> 
> So just set an environment variable in your cypress.config.js called grepIntegrationFolder pointing to the cypress folder. That's how I made it work.
> 
> ![image](https://user-images.githubusercontent.com/53126224/178961298-e07475ba-3801-4da3-90d8-0a999146d14c.png)
> 
> I hope this help someone 😁


Still facing the same issue. 
I have added grepIntegrationFolder: '../../', in the cypress.config.js file
<img width="554" alt="Screenshot 2022-07-14 at 4 14 09 PM" src="https://user-images.githubusercontent.com/105410226/178970669-d1b5b687-cfb1-464c-b908-75642ae504e9.png">


Probably its my path issue which I am not able to resolve as my Plugin > Index.js shows error on require('cypress-grep/src/plugin')(config) (pic attached)
<img width="1174" alt="Screenshot 2022-07-14 at 4 23 01 PM" src="https://user-images.githubusercontent.com/105410226/178971681-02eb813f-6b43-43d9-a421-6d74edda1366.png">
<img width="749" alt="Screenshot 2022-07-14 at 4 23 05 PM" src="https://user-images.githubusercontent.com/105410226/178971711-291ffdb8-fcf0-4efe-a9c1-45d4de498bee.png">

**Comment by GilbertoGNG** [comment]
@zubair-shahid-formsoft-inc-com I believe you should import the plugin in the setupNodeEvents function in your cypress.config.js instead of your plugins/index.js file. Actually with Cypress 10 you don't need the plugins/index.js file anymore.

Example:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/53126224/178983819-922e22cc-4e2e-4d08-a83a-f891bd9add76.png">

**Comment by zubair-shahid-formsoft-inc-com** [comment]
@GilbertoGNG I have imported everything under setupNodeEvents function in my cypress.config.js 
But I am still getting the same issue

<img width="685" alt="Screenshot 2022-07-14 at 6 46 54 PM" src="https://user-images.githubusercontent.com/105410226/178997884-509af03c-7401-4c0d-9a60-3ac316fd8500.png">


Using Command:  ./node_modules/.bin/cypress run --env grepTags="Smoke"
It executes all of the tests

> @zubair-shahid-formsoft-inc-com I believe you should import the plugin in the setupNodeEvents function in your cypress.config.js instead of your plugins/index.js file. Actually with Cypress 10 you don't need the plugins/index.js file anymore.
> 
> Example:
> 
> <img alt="image" width="655" src="https://user-images.githubusercontent.com/53126224/178983819-922e22cc-4e2e-4d08-a83a-f891bd9add76.png">

**Comment by joshuajtward** [comment]
> I double checked the plugin installation, and at least in my case it seems ok.
> 
> Here my e2e.js <img alt="e2e js_-_aristamd_-_Visual_Studio_Code_202207051657051279" width="432" src="https://user-images.githubusercontent.com/25928813/177408106-4e5ab050-7bc8-4ed9-b69a-d0f04e821316.png">
> 
> Here is my cypress.config.js <img alt="cypress config js_-_aristamd_-_Visual_Studio_Code_202207051657051384" width="369" src="https://user-images.githubusercontent.com/25928813/177408175-1386ce36-07da-4409-a43a-a2b3275df58b.png">
> 
> Here is output where it is finding all files in project now. I am only expecting 3 matches <img alt="package json_-_aristamd_-_Visual_Studio_Code_202207051657051809" width="376" src="https://user-images.githubusercontent.com/25928813/177408232-81a4bac3-f34a-4f2b-898e-1d502ecb929e.png">

@zubair-shahid-formsoft-inc-com from these screenshots it looks like Cypress might not be finding your support file, which would potentially cause the issues you are seeing...

**Comment by mmitchell3590** [comment]
Nice catch @joshuajtward -- I think you meant to tag me though, as those were my screenshots.
I have another config file that extends to the one I shared in the screenshot, and the support file path was not defined there. Everything is working as expected on my end now. Thank you!

**Comment by Showler** [comment]
@mmitchell3590 Working through the same issues you shared above, curious how you fixed the support file?

**Comment by joshuajtward** [comment]
Hi @Showler! I believe the problem @mmitchell3590 was facing was the line `supportFile: false` in the `cypress.config.js` file - `cypress-grep` needs the plugin to be registered in the support file in order to function properly

**Comment by Showler** [comment]
Thanks @joshuajtward that fixed the main issue. Now everything is running as expected! I did notice one interesting thing though. It appears that when passing in a config file the grep commands are not being recognized. 

Here is what I am seeing: 
1. This command is working as expected with no issues (from my package.json file)
`"cy:run:smoke" : "cypress run --env grepTags=@smoke,grepFilterSpecs=true`
2. This command is not working as expected. It appears to be finding all files with spec in the file name and running those. 
`"cy:run:sandbox-config:smoke": "cypress run --config-file cypress/configs/environment-configs/sandbox.config.js --env grepTags=@smoke,grepFilterSpecs=true"`

It is curious because my cypress.config.js and my sandbox.config.js file are the same. This is the contents of both config files. 
`const { defineConfig } = require('cypress')

  module.exports = defineConfig({
    e2e: {
      chromeWebSecurity: false,
      // Reporter options
      reporter: 'junit',
      reporterOptions: {
        outputs: true,
        attachments: true,
        includePending: true,
        testsuitesTitle: typeof(process.env.SUITE_NAME) != 'undefined' ? process.env.SUITE_NAME: "Cypress Tests " + new Date().toISOString(),
        rootSuiteTitle: "",
        mochaFile: 'cypress/results/test-results-[hash].xml',
      },
      baseUrl: "masking this url",
      specPattern: 'cypress/e2e/**/*spec.cy.js',
      // Import cypress plugins
      async setupNodeEvents(on, config) {
        // https://github.com/bahmutov/cypress-testrail-simple
        await require('cypress-testrail-simple/src/plugin')(on, config);
        await require('cypress-grep/src/plugin')(config);
        
        // make sure to return the config object
        // as it might have been modified by the plugin
        return config;
      },
    },
    env: {
      // Grep options for triggering tests
      grepFilterSpecs: true,
      grepOmitFiltered: true,
    }
})

**Comment by joshuajtward** [comment]
Glad to hear the main issue is resolved @Showler. As for the other problem with the other config file I'm not sure why it would be happening, do you get any insight if you run the command with `DEBUG=cypress-grep`?

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
