### ISSUE TITLE
The env variables should not be case sensitive

### ISSUE THREAD

**Issue by kishaningithub** [cypress-io/cypress-grep#141]
As per the below documentation the env variables will be given in "upper snake case" while the same in the env field in config will be in camel case

https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_

This plugin works if the env is exported like following

```
export CYPRESS_grepTags="@smoke"
```

but does not work if it is in upper snake case
```
export CYPRESS_GREP_TAGS="@smoke"
```

**Comment by joshuajtward** [comment]
It should be fairly straightforward to add this enhancement. You'll need to add the option to `src/plugin` and `src/support` in the relevant places.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
