### ISSUE TITLE
Should this work in parallel mode?

### ISSUE THREAD

**Issue by aangelinsf** [cypress-io/cypress-grep#143]
This doesn't appear to be working for me i.e. it runs all the tests rather than just those with the "smoke" tag.

`npx cypress run --config-file cypress-local.config.js --env cypress_host="http://www.site.com.docksal.site"  --env grepTags="smoke" --tag "smoke,local,2022-08-02,AVA" --record --key <redacted> --parallel --ci-build-id "2022-08-02 7:00:00"`

**Comment by joshuajtward** [comment]
Hi @aangelinsf! One immediate suspicion is that you are passing two `--env` flags, not sure if that will affect the tags getting picked up. If that is a red herring, please can you share the following to help debug:

- your config file
- your support file
- any debug output/error messages

**Comment by aangelinsf** [comment]
@joshuajtward we just re-worked our scripts to eliminate the need for the cypress_host variable and the plugin now works. I'm in love. Thank you.
