### ISSUE TITLE
Tags applied to suites makes webstorm IDE to not recognize the green arrow run tests button

### ISSUE THREAD

**Issue by tiagodread** [cypress-io/cypress-grep#145]
I realized that when you specify tags as options at suite level (on describe block) the green arrow button to trigger the test suite or a test case individually disappear.

![cypress](https://user-images.githubusercontent.com/12464858/186269828-29f71fc2-f2e4-4a95-8e81-9c48beb5b5c5.gif)

Is there any way to make webstorm recognize the run test button even passing config object to mocha describe block?

**Comment by joshuajtward** [comment]
Hi @tiagodread, I believe this should be raised with webstorm as this issue is not caused by this plugin, using these tags just highlights the problem
