### ISSUE TITLE
Further detail error surrounding 'no spec files were found' when spec files exist in other tag

### ISSUE THREAD

**Issue by jjorgenson-globality** [cypress-io/cypress-grep#146]
Example: one of our tests does not have a `@smoke` tag. When attempting to run with `grepTags="@smoke"` and `--spec "path/to/not-smoke-spec.js"`, this error occurs:

```
Can't run because no spec files were found.

We searched for specs matching this glob pattern:
<correct glob pattern>
```

Error should be something along the lines of "the spec defined does match have grep tags you used”

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
