### ISSUE TITLE
Tagged tests not running correctly / Setup issue / Debug module

### ISSUE THREAD

**Issue by antohayden** [cypress-io/cypress-grep#147]
Hi,

I was struggling with an issue where my tagged tests weren't running as I expected. It would run the entire file the test was tagged in rather than the individual tests. The env variables in cypress.config.ts were correct and I'm using the latest versions of Cypress (10.6.0) and this plugin. 
![image](https://user-images.githubusercontent.com/3662575/187898615-acd917e3-3589-45c7-9aec-16d7e7cd8ec9.png)

I eventually realised I had the below code in cypress/plugins/index.js instead of cypress/support/e2e.ts file incorrectly. 
![image](https://user-images.githubusercontent.com/3662575/187898777-a6db13bd-47e5-438e-aaca-43412fcb711d.png)

I configured e2e.ts as per the instructions but I ran into the below error..
![image](https://user-images.githubusercontent.com/3662575/187898523-d6a02367-3744-4f31-8d58-bcde2d285e20.png)

I then installed debug into the project 
`npm i --save-dev debug`

and tests tagged are now running as expected with the plugin. 

Just wanted to note this in case anyone else comes across a similar issue. <3

**Comment by Narretz** [comment]
cypress-grep has `debug` as a non-dev dependency, so maybe your node_modules got mixed up somehow.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
