### ISSUE TITLE
cypress-grep does not filter by mocha hooks on cypress.

### ISSUE THREAD

**Issue by raialmeida** [cypress-io/cypress-grep#148]
Hello,

cypress-grep does not execute by tags in beforeEach, afterEach, before, after, that is, when I pass the tag in hooks, it does not execute according to the tags.

Currently, regardless of the tag that will be passed, all hooks are executed.

Can you solve? or how can i solve this?
<img width="252" alt="image" src="https://user-images.githubusercontent.com/55969097/188736945-3ff0bf05-60dd-4142-907c-8570bb6aa88d.png">

**Comment by Narretz** [comment]
I would argue that this is out of scope of this plugin. hooks are notoriously fickle anyway.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
