### ISSUE TITLE
Suspected slowness when running perticular spec based on Tag vs running the perticular spec

### ISSUE THREAD

**Issue by SwardCoder** [cypress-io/cypress-grep#151]
i am suspecting filtering the spec and running only specific Spec via Grep is taking more time vs running spec directly with --spec 
is it expected or do we need to do something apart from using just cypress-grep

**Comment by joshuajtward** [comment]
Hi @SwardCoder! Are you using the `grepFilterSpecs` and `grepOmitFiltered` flags/env vars? If not then that might be the reason it's running slower. If that doesn't fix it can you share some config/debug logs?

**Comment by SwardCoder** [comment]
I was using cypress-grep plugin from cypress. Io

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
