### ISSUE TITLE
Deprecate Repo

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress-grep#153]
We moved this project to the main Cypress monorepo at `npm/grep`. We need document in this repo that it is deprecated, triage and old issues and add https://docs.npmjs.com/cli/v8/commands/npm-deprecate/

**Comment by admah** [comment]
TODO: 

- [x] add npm-deprecate package
- [x] update the README with new location and link to create issues
- [ ] set repo to archived
- [x] work through issues using [Icewatch guide](https://github.com/cypress-io/prod-eng-docs/blob/main/cypress-app/ice-watch-process.md)
- [x] comment on this letting Chris G know it is not needed now - https://github.com/cypress-io/cypress-grep/pull/152

**Comment by jordanpowell88** [comment]
I'm currently blocked as I do not have permissions to make the `cypress-grep` repo archived
