### ISSUE TITLE
Can't run two "not" tags

### ISSUE THREAD

**Issue by ivanomilo** [cypress-io/cypress-grep#154]
tried all combinations of grepTags="-@BUGS -@SMOKE", grepTags=-@BUGS, -@SMOKE ,  grepTags="-@BUGS; -@SMOKE",   grepTags="--@BUGS --@SMOKE". the only thing that seems to work is using grepTags twice in the command line arg. is there a way to specify an OR for a NOT tag command in one string?

**Comment by pmweeks98** [comment]
Have you tried grepTags="-@bugs --@smoke"
Ie one inverted tag with one NOT tag? 

#137 or #149 should fix this issue

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
