### ISSUE TITLE
Flitering out tests within test suite describe

### ISSUE THREAD

**Issue by Gayathri-Kesavakannan** [cypress-io/cypress-grep#156]
I have test suite as 

describe('block for config', {tags: '@smoke'}, () => {
  it('should run', {tags: '@smoke'},() => {})

  it('should also work', {tags: '@skip'},() => {})
})

I want to run first test but skip second test with tag @skip 
Is this possible ? 
I tried --env grepTags='@smoke+-@skip' but still it's running entire test suite with both test

**Comment by joshuajtward** [comment]
As a workaround, this should work: 

```
describe('block for config', () => {
it('should run', {tags: '@smoke'},() => {})

it('should also work', {tags: '@Skip'},() => {})
})
```

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
