### ISSUE TITLE
Type error when registering cypress-grep

### ISSUE THREAD

**Issue by richardszanyi-kasa** [cypress-io/cypress-grep#158]
TS throws error seen on the screenshot when importing cypress-grep.

![image](https://user-images.githubusercontent.com/101114202/196393280-7d1cee1f-2e3a-4f7b-864a-3f9b3747abbe.png)

Same error as seen here: https://github.com/cypress-io/cypress-grep/issues/71

**Comment by clazette** [comment]
I have version 3.0.3 installed and the issue remains.

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). If this is still an issue with the new package, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
