### ISSUE TITLE
typescript is always return error about the tags object if we don't add //@ts-ignore

### ISSUE THREAD

**Issue by idanElitzur** [cypress-io/cypress-grep#166]
Intellj always return a typescript error about the object of tags even it's defined as "type" inside the typescript compiler configurat file and also is part of the "include" files.
please your assistance.

![Screenshot 2022-12-05 at 12 16 01](https://user-images.githubusercontent.com/104420464/205612392-9a7490ba-6a97-4537-bba1-db99b8c1b877.png)

**Comment by alexandreedgeiq** [comment]
I'm experiencing the same issue with .ts files.
Cypress: 11.2.0
"cypress-grep": 3.1.0

But I found a solution to this issue.
In my e2e.ts I used: 
       **require('@cypress/grep')();**
And in my tsconfig.json inside Types, I included **"@cypress/grep"**

![image](https://user-images.githubusercontent.com/112183797/206281679-2ea2f4c1-a36b-4ce4-a9c0-68b6ca5f3621.png)

**Comment by Kosai106** [comment]
As @alexandreedgeiq pointed out, you need to:

1. Update to the latest version

2. Add `@cypress/grep` to your `tsconfig.json`

3. add the following to the top of your `commands.d.ts` file:

```ts
/// <reference types="@cypress/grep" />;
```

**Comment by richardszanyi-kasa** [comment]
> As @alexandreedgeiq pointed out, you need to:
> 
> 1. Update to the latest version
> 2. Add `@cypress/grep` to your `tsconfig.json`
> 3. add the following to the top of your `commands.d.ts` file:
> 
> ```ts
> /// <reference types="@cypress/grep" />;
> ```

Where can we find this command.d.ts file? 
I only got support/commands.ts

**Comment by Kosai106** [comment]
@richardszanyi-kasa https://docs.cypress.io/guides/tooling/typescript-support#Using-an-External-Typings-File

**Comment by idanElitzur** [comment]
Thanks for your answer.
I've already try all of these ways but something wrong with this package.

**Comment by richardszanyi-kasa** [comment]
@Kosai106 
![image](https://user-images.githubusercontent.com/101114202/211290087-f5da7ab9-b769-4843-a119-e7bf41ba5e55.png)

It throws me an error like that. 

Cypress v11.3.0
