### ISSUE TITLE
add suport to context block

### ISSUE THREAD

**Issue by millnitzluan** [cypress-io/cypress-grep#47]
As cypress has support Mocha bdd syntax would be interesting to add it in this lib.
https://docs.cypress.io/guides/references/bundled-tools#Mocha

**Comment by millnitzluan** [comment]
If you think that it would be useful I would love to work on it.

**Comment by bahmutov** [comment]
How is this different from #22 and https://github.com/bahmutov/cypress-grep#test-suites?
