### ISSUE TITLE
in Cypress version 3.7.0: Uncaught TypeError: fn.call is not a function

### ISSUE THREAD

**Issue by yasserfaraazkhan** [cypress-io/cypress-grep#56]
Cypress: version: 3.7.0
Cypress grep: 2.5.1
Node: 12.18.0
Run command: 
```
./node_modules/.bin/cypress run --env grep=A --spec '**/**/test.spec.js'
```

**my Test file:**
```
describe('A', () => {
  it('B', { tags: '@test' }, () => {
    console.log('in B');
  });
  it('C', { tags: ['@test', '@smoke'] }, () => {
    console.log('in C');
  });
});
```
**Error log:**
```
 1) An uncaught error was detected outside of a test:
     Uncaught TypeError: fn.call is not a function

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at context.describe.context.context (http://localhost:9090/__cypress/runner/cypress_runner.js:27045:10)
```
![image](https://user-images.githubusercontent.com/15979783/124513720-10009180-ddf9-11eb-9ee2-566d6d107c59.png)

**Comment by bahmutov** [comment]
Can you try a newer Cypress version (which is 7 now), version 3 is very very old and I don’t see this plug-in providing support for such an old test runner

**Comment by yasserfaraazkhan** [comment]
@bahmutov 
In one of my projects it's working seamless with new version. 
But one of the main projects i'm working on is in legacy angular any not likely to upgrade.

I was hoping we can have a custom way of overriding `it` block. ( I think this is doable).
My blocker in above approach is, how to let Cypress.run() to run or skip that particular it block
