### ISSUE TITLE
it.only() Skips Tests with No Output

### ISSUE THREAD

**Issue by J-Harms** [cypress-io/cypress-grep#57]
**Issue:**
When using a configFile that contains the desired grepTags, and attempting to utilize it.only() in order to debug tests, if the test case has a matching grep it opens but is skipped with zero output.

**Desired result:**
it.only() with a matching grepTag should run the test case.

**Information to recreate:**
cypress version 7.30
cypress-grep version 2.5.2

cypressGrep.json (configFile with grepTags):
```
{
    "baseUrl": "https://github.com/cypress-io/cypress-grep",
    "env": {
        "grepTags": "foo"
    }
}
```

login.spec.js (test file with correct tag):
```
describe('Login Tests', () => {
    
    it.only('Open github',{ tags:['foo'] }, () => {
        cy.visit('/');
    });
});
```
Command:
```
npx cypress open --env configFile=cypressGrep
```

Result:
![image](https://user-images.githubusercontent.com/87548335/126009562-ee8bc5ae-0b62-4934-8c6d-6e306e9a9e53.png)

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
