### ISSUE TITLE
GrepTags doesn't work with multiple env configuration files

### ISSUE THREAD

**Issue by BrunoNelli** [cypress-io/cypress-grep#58]
**Issue:**
When using a multiple configuration file with configFile and grepTags it doesn't work properly filtering the tag and applying ENV.

**Desired result:**
Execute tests with the env variable and filter scenarios with tags at same execution

Information to recreate:
cypress version 7.30
cypress-grep version 2.5.2

Need a project multiple configuration files to use --env configFile=ENV
https://docs.cypress.io/api/plugins/configuration-api#Switch-between-multiple-configuration-files

I have uploaded a project to reproduce the issue:
https://github.com/BrunoNelli/grep_issue

**Comment by J-Harms** [comment]
In the project repo you mention some commands that did not work. I am curious if this command would work with it?

`npx cypress run --env grepTags=@TES-T5967,configFile=HMP`

https://docs.cypress.io/guides/guides/command-line#cypress-run-env-lt-env-gt:
"Pass several variables using commas and no spaces. Numbers are automatically converted from strings.
`cypress run --env host=api.dev.local,port=4222`"

**Comment by BrunoNelli** [comment]
> In the project repo you mention some commands that did not work. I am curious if this command would work with it?
> 
> `npx cypress run --env grepTags=@TES-T5967,configFile=HMP`
> 
> https://docs.cypress.io/guides/guides/command-line#cypress-run-env-lt-env-gt:
> "Pass several variables using commas and no spaces. Numbers are automatically converted from strings.
> `cypress run --env host=api.dev.local,port=4222`"

Thanks @J-Harms, it worked as I need.
