### ISSUE TITLE
before() block does not get executed when some tests are skipped

### ISSUE THREAD

**Issue by pavelsaman** [cypress-io/cypress-grep#61]
I have a spec file:

```javascript
describe('Update ad', () => {

    before(() => {
        
    });

    beforeEach(() => {
        
    });

    it('A', { tags: ['@ad'] }, () => {
        
    });
    
    it('B', { tags: ['@core', '@ad', '@staging'] }, () => {
       
    });
});
```

I run it with this command:

```
$ cypress run --browser chrome --headless --env grepTags=@staging
```

The point is to run only the second test on the staging environment.

**The problem is that `before()` block does not execute in this scenario.**

When I add tag `@staging` to the first test as well:

```javascript
describe('Update ad', () => {

    before(() => {
        
    });

    beforeEach(() => {
        
    });

    it('A', { tags: ['@ad', '@staging'] }, () => {
        
    });
    
    it('B', { tags: ['@core', '@ad', '@staging'] }, () => {
       
    });
});
```

the `before()` block gets executed.

When I reorder the test cases, so that B goes before A:

```javascript
describe('Update ad', () => {

    before(() => {
        
    });

    beforeEach(() => {
        
    });

    it('B', { tags: ['@core', '@ad', '@staging'] }, () => {
       
    });

    it('A', { tags: ['@ad'] }, () => {
        
    });
});
```

the `before()` block also gets executed.

I find this a strange behaviour, I expect the `before()` block to get executed no matter how my tests are ordered; skipping some tests should not be a problem either.

**Comment by missing1984** [comment]
ran into the same issue

**Comment by pavelsaman** [comment]
I've also checked the I use the latest version of cypress-grep, that is 2.5.3. I didn't include this information in my previous post.

**Comment by Narretz** [comment]
I just tried this with the latest cypress-grep and it works as expected
