### ISSUE TITLE
How can I repeatedly run/burn a scenario (written in cucumber) for a specific number of times through cypress-grep?

### ISSUE THREAD

**Issue by praveenpandey02** [cypress-io/cypress-grep#62]
I have installed `cypress-grep` plugin as a dev dependency so that I can run a cucumber scenario a specific number of times to check its flakiness. These are the changes I have made:
1. `yarn add -D cypress-grep` which adds this dependency in `package.json`
2. Made this entry `require('cypress-grep')()` in `cypress/support > index.js`
3. Optionally, also made the following below entry here `cypress/plugins > index.js`
```
module.exports = (on, config) => {
  require('cypress-grep/src/plugin')(config)
}
```
4. Now I am trying to run a scenario (title contains "hello") inside a feature file multiple times to check its flakiness `cypress/integration/folderA/sample.feature`. For this, I am executing the following command:
`npx cypress run --spec "cypress/integration/folderA/sample.feature" --env grep=hello,burn=10`

But every time the command runs, I get the following error:
```
The error was:

Error: Webpack Compilation Error
./cypress/integration/folderA/sample.feature 1:15
Module parse failed: Unexpected token (1:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Feature: Feature file name
| 
|   Background: Sample background title

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

I am not sure what this error is trying to tell me and how do I fix it.
P.S: I have even referred this but it only talks about spec (.js) files and not feature (.feature) files: https://glebbahmutov.com/blog/burning-tests/

**Comment by bahmutov** [comment]
Since I don't use cucumber, have you set up the cucumber preprocessor that loads the .feature files in Cypress?

**Comment by praveenpandey02** [comment]
> Since I don't use cucumber, have you set up the cucumber preprocessor that loads the .feature files in Cypress?
> 
> 
Yes I've set it up and my feature files otherwise run perfectly fine.

**Comment by bahmutov** [comment]
ok, in that case can you provide a reproduction repo with cucumber working but then adding cypress-grep and it stops working?

**Comment by praveenpandey02** [comment]
Sure I can do that.

**Comment by praveenpandey02** [comment]
Sorry. It took me sometime to get back to you. Here is the repo link: https://github.com/praveenpandey02/plug_it. I had to create a new repo due to data sensitivity issue but the error I get is exactly the same. This repo was tested both with `cypress-grep plugin` and without it. Unfortunately, it does not work with `cypress-grep`.

**Comment by praveenpandey02** [comment]
Hi @bahmutov. We are looking forward to your suggestion here.

**Comment by praveenpandey02** [comment]
Still no luck! It works with spec files and not with feature files :(

**Comment by praveenpandey02** [comment]
So, I finally made it work and what a silly mistake I've been making all this while 🤦‍♂️. So this was wrong: 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/75299617/130731852-69fac6f3-4468-4ebc-8711-7fdc4830f35f.png">

Instead, I had to do this:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/75299617/130732022-aecf16c5-e9eb-4b17-9860-342fc920afe9.png">

This is the result. All green:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/75299617/130732122-deaf7742-c20c-4d25-b1ca-0aa07c48ce01.png">

**Comment by bahmutov** [comment]
👍
