### ISSUE TITLE
Make compatible with it.only

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-grep#74]
Right now having grep + it.only crashes the test runner

<img width="812" alt="Screen Shot 2021-10-26 at 12 55 05" src="https://user-images.githubusercontent.com/2212006/138926247-cd117426-fb59-4480-aea4-560f42bba059.png">

**Comment by jordanpowell88** [comment]
We are in the process of deprecating this repo as this package has been republished under `@cypress/grep` and has moved to [https://github.com/cypress-io/cypress/tree/develop/npm/grep](https://github.com/cypress-io/cypress/tree/develop/npm/grep). I'm going to go ahead and close this issue as it appears stale. If this is still an issue, please open a new issue [here](https://github.com/cypress-io/cypress/issues/new/choose)
