### ISSUE TITLE
Can't run grepFilterSpecs and grepOmitFiltered

### ISSUE THREAD

**Issue by darioprinc** [cypress-io/cypress-grep#87]
Hi, I am struggling to run the **grepFilterSpecs** and **grepOmitFiltered** options.

Can't get it to work, not in CI, but mainly not even locally. 

```
plugins/index.js

config.env.grepTags = '@smoke';
config.env.grepFilterSpecs = true;
config.env.grepOmitFiltered = true;
```
or
```
CLI

npx cypress run --env grepTags=@smoke,grepFilterSpecs=true,grepOmitFiltered=true
```
or
```
cypress.json

{
  "env": {
    "grepTags": "@smoke",
    "grepFilterSpecs": true,
    "grepOmitFiltered": true
  }
}
```

What is interesting - the configurations above will correctly run only tests with a @smoke tag, but the grepFilterSpecs and grepOmitFiltered are not taken into account. The output still shows pending tests both in run mode and in GUI:

![image](https://user-images.githubusercontent.com/35229102/140504975-138e51bc-f448-4cfe-b095-db3dfc8a6263.png)

**Expected**: Tests without the @smoke tag should not be skipped (pending) but ommited.

The plugin is registered in plugins/index.js `require('cypress-grep/src/plugin')(config);`
Cypress v. 8.7.0

Any hint will be appreciated.

Cheers, Dario

**Comment by darioprinc** [comment]
Sure:

```
import { prepareTags } from '../support/grepTags/prepareTags';

module.exports = async (on, config) => {
  require('cypress-grep/src/plugin')(config);

  const location = config.env.location || 'develop';

  config.env = require(`../config/${location}.json`);

  config.retries = config.env.retries;

  config.baseUrl = config.env.baseUrl;

  // runs only in CI
  if (process.env.CI_MERGE_REQUEST_DIFF_BASE_SHA && process.env.CI_COMMIT_SHA) {
    config.env.grepTags = await prepareTags(); // this returns a string, e.g. '@react @smoke'
    config.env.grepFilterSpecs = true;
    config.env.grepOmitFiltered = true;
  }

  return config;
};
```

**Comment by Gayathri-Kesavakannan** [comment]
Facing same issue ,  filtering using tag “smoke” filtering specs using tag “smoke”
Couldn’t determine file 

cypress run grepTags=smoke is working fine runs only smoke test but moves other tests to Pending

cypress run grepTags=smoke,grepFilterSpecs=true - this is not working. Couldn’t determine test names in file 

not sure what am missing here

**Comment by bahmutov** [comment]
Please look at the debugging section of the readme

**Comment by darioprinc** [comment]
Yep, everything in place:

![image](https://user-images.githubusercontent.com/35229102/141303934-a03f75fb-f20f-46ee-846c-001c15308287.png)

The tests run by tag but the rest is still skipped:

![image](https://user-images.githubusercontent.com/35229102/141304058-a900de2f-cfe5-4289-b470-895a3053ae6f.png)

**Comment by bahmutov** [comment]
Can you. show the debug output in the browser? https://github.com/cypress-io/cypress-grep#debugging-in-the-browser

**Comment by darioprinc** [comment]
Can't see the options there:

![image](https://user-images.githubusercontent.com/35229102/141454289-1536c526-a493-4fda-8246-308a7763fa83.png)

**Comment by bahmutov** [comment]
Can you check the plugin version you are using? https://github.com/cypress-io/cypress-grep#debugging

**Comment by darioprinc** [comment]
well, version upgrade solved it. thanks a lot!

**Comment by dkoudrinhc** [comment]
I'm having a similar issue where it IS running my tagged tests, but the omitFiltered=true flag isn't being picked up for some reason.

**Comment by darioprinc** [comment]
did you follow the steps above? register in plugins, upgrade package to the latest version etc? you got the flag name right - _grepOmitFiltered_ ?

**Comment by dkoudrinhc** [comment]
Yep, I think I got it working after a day of trial and error.

**Comment by EvgeniyGordinskiy** [comment]
grepOmitFiltered doesn't work.
I've checked all possible solutions above: registered in plugins, installed the latest version (2.13.1), checked the flag names.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/25403520/169498316-b64e2575-ed0b-4a53-8db4-12f90cc90d3e.png">
