### ISSUE TITLE
`before` and `after` hooks always get called even spec (`describe` or `it`) doesn't have targeted tags

### ISSUE THREAD

**Issue by hiendnguyen** [cypress-io/cypress-grep#90]
Below is sample spec

```
// test.ts
describe('Template', { tags: '@p100' }, () => {
  before(() => {
    console.log('before all book')
  })

  beforeEach(() => {
    console.log('beforeEach hook')
  })

  afterEach(() => {
    console.log('afterEach hook')
  })

  after(() => {
    console.log('after all hook')
  })

  it('test case 01', () => {
    console.log('ahh, test case')
  })
})
```

Open runner by calling `npx cypress open --env grepTags=@smoke` and run `test.ts` spec by clicking on it on runner

Observe that `before` and `after` hooks get called
![image](https://user-images.githubusercontent.com/7049357/142555324-1a4048f1-68c4-49d2-aa10-83f477147903.png)

**Comment by thetif** [comment]
I am also have this issue.

**Comment by wqsandoval** [comment]
I have the same issue , all before hooks are called making our build pipeline take much longer than needed

**Comment by rgschulte** [comment]
I am having the same issue. Before's are called making building waaaaaaay longer than expected

**Comment by hiendnguyen** [comment]
The below combination is working for me
- cypress-grep 2.10.2
- `--env grepTags=@smoke,grepOmitFiltered=true`
