### ISSUE TITLE
grepFilterSpecs not working with multiple tags

### ISSUE THREAD

**Issue by Olavarry** [cypress-io/cypress-grep#98]
I have two specs with different tags:

**cypress.env.json file:**
{
  "skipAccessChecks": false,
  "test_env": "prod",
  "grepOmitFiltered": true,
  "grepFilterSpecs": true
}

**test1.spec.js:**
```
describe('Test 1', { tags: '#tag1'}, () => {
expect(true).to.be.true
})
```

**test2.spec.js:**
```
describe('Test2', { tags: '#tag2'}, () => {
expect(true).to.be.true
})
```

**Then I'm trying to run with this command:**
`npm run cy:test -- --env grepTags='#tag1+#tag2'`

**This is being printed out when execution starts:**
```
cypress-grep: filtering using tag "#tag1+#tag2"
cypress-grep: will omit filtered tests
cypress-grep: filtering specs using tag "#tag1+#tag2"
Grep "undefined" has eliminated all specs
Will leave all specs to run to filter at run-time
```

**If I remove one of the tags it works fine:**

```
npm run cy:test -- --env grepTags='#tag1'

cypress-grep: filtering using tag "#tag1"
cypress-grep: will omit filtered tests
cypress-grep: filtering specs using tag "#tag1"
```

**Comment by bahmutov** [comment]
Are you trying to run tests that have Tag1 OR tests Tag2?

**Comment by Olavarry** [comment]
I have tried both AND and OR and getting the same result

**Comment by Olavarry** [comment]
I should have given the OR example, as AND will not find any test with both tags, sorry I just wanted to give the 'example'
 but OR should filter and run only these 2 specs, right? buit it is not and it throws the message:
```
Grep "undefined" has eliminated all specs
Will leave all specs to run to filter at run-time
```

**Comment by Olavarry** [comment]
Thanks for the quick fix, this is a great plugin thanks a lot for your work!
